### ISSUE TITLE
5.3 compat

### ISSUE THREAD

**Issue by TomHAnderson** [phpro/zf-doctrine-hydration-module#14]
zf-apigility-doctrine, along with the rest of zfcampus, aims for php 5.3 compatibility.  I'd like to edit this down but wanted to get a go-ahead from you @veewee first.  Are you OK with moving this back to a 5.3 min?

**Comment by veewee** [comment]
Hello @TomHAnderson 

Zend Framework is dropping 5.3 support:
https://github.com/zendframework/zf2/issues/7095

This means that apigility and zf-campus will also need to bump the version to 5.4. Otherwise it won't be able to use some ZF2 components.

So I am not sure if it is wort the time to convert the code to be php 5.3 compatible.
On the other hand: I guess this module could be 5.3 compatible by only changing the short array syntax.

So if you got time and want to implement it: then it's fine by me. It's your call! :)

**Comment by veewee** [comment]
Thanks @TomHAnderson!
I will tag a new version later today when I have done some extra tests.
